from datetime import datetime, timezone
from decimal import Decimal
from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, Field


class MarketRegime(str, Enum):
    TREND_UP = "TREND_UP"
    TREND_DOWN = "TREND_DOWN"
    SIDEWAYS = "SIDEWAYS"
    HIGH_VOLATILITY = "HIGH_VOLATILITY"
    LOW_VOLATILITY = "LOW_VOLATILITY"
    LIQUIDITY_RISK = "LIQUIDITY_RISK"
    UNKNOWN = "UNKNOWN"


class SignalAction(str, Enum):
    LONG = "LONG"
    SHORT = "SHORT"  # In Spot MVP, SHORT is an exit signal
    FLAT = "FLAT"


class AgentSignal(BaseModel):
    """Output generated by Alpha Agents."""
    agent_id: str
    symbol: str
    action: SignalAction
    expected_return_bps: float
    confidence: float  # Range: [0.0, 1.0]
    horizon_minutes: int
    invalidation_price: Decimal
    suggested_stop_price: Decimal
    suggested_take_profit_price: Decimal
    reasons: List[str] = Field(default_factory=list)
    feature_timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    strategy_version: str = "1.0.0"


class CriticDecision(BaseModel):
    """Output from the Critic Agent scrutinizing trade proposals."""
    approved: bool
    risk_flags: List[str] = Field(default_factory=list)
    confidence_penalty: float = 0.0
    rejection_reason: Optional[str] = None
    evaluated_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
