from datetime import datetime, timezone
from decimal import Decimal
from enum import Enum
from typing import List, Optional
from uuid import UUID, uuid4

from pydantic import BaseModel, Field

from packages.schemas.execution import OrderSide


class ExitReason(str, Enum):
    HARD_STOP = "HARD_STOP"
    VOLATILITY_STOP = "VOLATILITY_STOP"
    TAKE_PROFIT = "TAKE_PROFIT"
    TRAILING_STOP = "TRAILING_STOP"
    TIME_STOP = "TIME_STOP"
    SIGNAL_DECAY = "SIGNAL_DECAY"
    SIGNAL_REVERSAL = "SIGNAL_REVERSAL"
    REGIME_EXIT = "REGIME_EXIT"
    PORTFOLIO_RISK = "PORTFOLIO_RISK"
    DAILY_LOSS_LIMIT = "DAILY_LOSS_LIMIT"
    EMERGENCY_STOP = "EMERGENCY_STOP"


class Position(BaseModel):
    """Open or closed trading position."""
    position_id: UUID = Field(default_factory=uuid4)
    symbol: str
    side: OrderSide
    quantity: Decimal
    entry_price: Decimal
    average_fill_price: Decimal
    current_price: Decimal
    current_stop: Decimal
    initial_stop: Decimal
    take_profit: Decimal
    highest_price_since_entry: Decimal
    lowest_price_since_entry: Decimal
    unrealized_pnl: Decimal = Decimal("0")
    realized_pnl: Decimal = Decimal("0")
    fees: Decimal = Decimal("0")
    slippage_bps: float = 0.0
    strategy_attribution: List[str] = Field(default_factory=list)
    opened_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    last_evaluated_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    is_open: bool = True
    exit_reason: Optional[ExitReason] = None
    closed_at: Optional[datetime] = None


class PortfolioSnapshot(BaseModel):
    """Portfolio state snapshot."""
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    total_nav: Decimal
    cash_balance: Decimal
    unrealized_pnl: Decimal
    realized_pnl_today: Decimal
    current_drawdown_pct: float
    open_positions_count: int
    open_risk_pct: float
    is_kill_switch_active: bool = False
    system_mode: str = "PAPER_TRADING"


class ExitDecision(BaseModel):
    """Exit recommendation generated by Position Manager."""
    position_id: UUID
    symbol: str
    should_exit: bool
    exit_reason: ExitReason
    target_price: Decimal
    confidence: float
    evaluated_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
