from datetime import datetime, timedelta, timezone
from decimal import Decimal
from typing import List
from uuid import UUID, uuid4

from pydantic import BaseModel, Field

from packages.schemas.execution import OrderSide


class TradeIntent(BaseModel):
    """Trade proposal generated by Meta Allocator submitted to Risk Governor."""
    intent_id: UUID = Field(default_factory=uuid4)
    symbol: str
    side: OrderSide
    strategy_ids: List[str] = Field(default_factory=list)
    expected_return_bps: float
    confidence: float
    entry_price_reference: Decimal
    stop_price: Decimal
    take_profit_price: Decimal
    maximum_holding_minutes: int = 240
    maximum_entry_slippage_bps: float = 10.0
    feature_timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    expires_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc) + timedelta(minutes=5)
    )
    reason_codes: List[str] = Field(default_factory=list)
